### ISSUE TITLE
CI/CD setup

### ISSUE THREAD

**Issue by ffxsam** [kamilogorek/sentry-vue-sourcemaps#1]
Hopefully this is helpful to someone, but I managed to get releases & source maps working in a CI/CD environment (in this case, AWS Amplify Console). @kamilogorek let me know if any of this looks wrong, please. 😄 

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - export VUE_APP_RELEASE=$(yarn -s sentry-cli releases propose-version)
        - yarn sentry-cli releases new $VUE_APP_RELEASE
        - yarn sentry-cli releases set-commits --auto $VUE_APP_RELEASE
        - yarn run build
        - yarn sentry-cli releases files $VUE_APP_RELEASE upload-sourcemaps ./dist --rewrite
        - yarn sentry-cli releases finalize $VUE_APP_RELEASE
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
